// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvv7SJIM7k7F0-oBuoVR7iNuL_oUQlkxk',
    appId: '1:340073529659:web:9137197ac8391d96ddb71e',
    messagingSenderId: '340073529659',
    projectId: 'revy-dev-0',
    authDomain: 'revy-dev-0.firebaseapp.com',
    storageBucket: 'revy-dev-0.appspot.com',
    measurementId: 'G-MX5D9VBWCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46-nJIU2ViqLdZV9_MuaFALZ_LXZS7Ss',
    appId: '1:340073529659:android:56b82a57f8d7a1bbddb71e',
    messagingSenderId: '340073529659',
    projectId: 'revy-dev-0',
    storageBucket: 'revy-dev-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJK_1e21nd4qWXb3B4ULO89rDh8fC3zsg',
    appId: '1:340073529659:ios:8b95ebe3f8eed8f7ddb71e',
    messagingSenderId: '340073529659',
    projectId: 'revy-dev-0',
    storageBucket: 'revy-dev-0.appspot.com',
    iosBundleId: 'com.nidec-drives.revy',
  );

}